### ISSUE TITLE
Improve error message when mycoind was started without init before

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#94]
Current output:
```
I[08-27|14:27:49.336] Info synced                                  module=mycoin height=0 hash=
panic: unexpected end of JSON input

goroutine 51 [running]:
github.com/iov-one/weave/app.(*StoreApp).InitChain(0xc4202240a0, 0x5b8409a8, 0xc4201e8600, 0x11, 0xc4201d83c0, 0xc4201dabe0, 0x1, 0x1, 0x0, 0x0, ...)
    /Users/alex/workspace/go/src/github.com/iov-one/weave/app/store.go:304 +0xbc
github.com/iov-one/weave/vendor/github.com/tendermint/abci/server.(*SocketServer).handleRequest(0xc420224140, 0xc4201d25e0, 0xc4200b2a80)
    /Users/alex/workspace/go/src/github.com/iov-one/weave/vendor/github.com/tendermint/abci/server/socket_server.go:193 +0x76b
github.com/iov-one/weave/vendor/github.com/tendermint/abci/server.(*SocketServer).handleRequests(0xc420224140, 0xc4200b2a20, 0x16aa280, 0xc4200aa048, 0xc4200b2a80)
    /Users/alex/workspace/go/src/github.com/iov-one/weave/vendor/github.com/tendermint/abci/server/socket_server.go:163 +0xe8
created by github.com/iov-one/weave/vendor/github.com/tendermint/abci/server.(*SocketServer).acceptConnectionsRoutine
    /Users/alex/workspace/go/src/github.com/iov-one/weave/vendor/github.com/tendermint/abci/server/socket_server.go:119 +0x269
```

**Comment by ethanfrey** [comment]
Responsible code is here: https://github.com/iov-one/weave/blob/master/app/store.go#L103-L120

If we just check for empty state before trying to parse, we can return a clearer error, like
`app_state not set in genesis.json, please initialize application before launching the blockchain`
